### ISSUE TITLE
Přidávání OCR

### ISSUE THREAD

**Issue by MartinRumanek** [moravianlibrary/K4-tools#6]
Upravit přidávání OCR tak, aby bylo schopné využívat https://github.com/moravianlibrary/AbbyyRest.

Mělo by to fungovat malinko jinak, mezi vložením obrázku a vytáhnutím OCR může uplynout netriviální čas. Klidně to může být jako zvláštní skript.

**Comment by Jenyk** [comment]
Hotovo: https://github.com/moravianlibrary/K4-tools/commit/f27d741b111a35d2899016b07fb7b6e26663443f
Využívá Spring Batch
