### ISSUE TITLE
Vyčlenit volání remote client API do zvláštní knihovny

### ISSUE THREAD

**Issue by MartinRumanek** [moravianlibrary/K4-tools#7]
Udělat zvláštní jar knihovnu s pěkně navrženým api, která bude obsahovat volání do Kramerius remote api.

Měla by zvládat:
* pustit jakýkoliv typ reindexace
* umožnit sledovat stav (planned, running, failed, warning)

**Comment by MartinRumanek** [comment]
Protože volání na LR servlet nefunguje dobře a ať neduplikujeme kód zde a v editoru. Vyřeším pomocí toho issue https://github.com/moravianlibrary/MEditor/issues/37

**Comment by Jenyk** [comment]
https://github.com/moravianlibrary/K4-tools/commit/8170285e09de78dff7db7d7efd42766b74bd2223
